apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firtsapp-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ines312692/Multi-Cloud-Kubernetes-CI-CD-Infrastructure-with-Terraform-and-GitOps.git
    targetRevision: main
    path: infra/k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true